seed: 42

num_steps: 1000000
save_ckpt_interval: 100000

batch_size: 8
num_workers: 4

loss_coef:
  mel: 45.0
  fm: 2.0
  var: 1.0
  align: 2.0

frame_segment_size: 32
sample_segment_size: 7680  # frame_segment_size * hop_length
