defaults:
  - _self_
  - path: default
  - train: default
  - mel: default
  - dataset: default
  - generator: default
  - discriminator: default
  - optimizer: adamw
  - scheduler: exponential
  - lit_module: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: ./
  output_subdir: null

preprocess:
  overwrite: true
  n_jobs: 8

train:
  out_dir: ./out

syn:
  out_dir: ./out
  ckpt_path: ../01_train/out/ckpt/last.ckpt
